### ISSUE TITLE
Missing question marks in confirmation prompts

### ISSUE THREAD

**Issue by iamthad** [pizzapanther/neutron-manager#1]
These prompts don't end in question marks. I admit that this is trivial.

https://github.com/pizzapanther/neutron-manager/blob/7d7c673e7247dafd25e78306db294015a0293017/nmanage/resources/templates/resources/info.html#L93

https://github.com/pizzapanther/neutron-manager/blob/f3e77848f3a7e5152db35867c74f15cdd64092aa/nmanage/resources/templates/resources/list.html#L107

**Comment by pizzapanther** [comment]
All things start small!
